---
name: Run tests and lint

on:
  pull_request:
    branches:
      - main

jobs:
  commitlint:
    name: Commit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5

  dependency:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run install dep
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm install

  lint:
    name: Lint
    needs: [commitlint, dependency]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Cache Nx
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/nx
          key: cache-nx
          restore-keys: |
            cache-nx--
      - name: Run effected Lint
        run: npx nx affected -t lint --parallel --configuration=ci --base=origin/main --head=${{ github.sha }}

  test:
    name: Test
    needs: [commitlint, dependency]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Cache Nx
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/nx
          key: cache-nx-test
          restore-keys: |
            cache-nx-test--
      - name: Run effected Test
        run: npx nx affected -t test --parallel --configuration=ci --base=origin/main --head=${{ github.sha }}
